HUB-4276: require org.knime.core-4.7.2
Update from 4.7.0 -> 4.7.2 is not guaranteeing that core is updated, as
per:
2023-05-04 17:33:32,366 : ERROR : main :  :
CreateMetaNodeTemplateCommand :  :  : Metanode loading failed with
NoSuchMethodError: 'void
org.knime.core.util.pathresolve.URIToFileResolve$KNIMEURIDescription.<init>(java.lang.String,
java.lang.String)'
java.lang.NoSuchMethodError: 'void
org.knime.core.util.pathresolve.URIToFileResolve$KNIMEURIDescription.<init>(java.lang.String,
java.lang.String)'
	at org.knime.workbench.explorer.pathresolve.URIToFileResolveImpl.toDescription(URIToFileResolveImpl.java:299)
	at org.knime.core.util.pathresolve.ResolverUtil.toDescription(ResolverUtil.java:282)
	at org.knime.core.node.workflow.WorkflowLoadHelper.createTemplateLoadPersistor(WorkflowLoadHelper.java:443)

HUB-4276 (Components from other user spaces cannot be updated)